// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CreateChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid ( ), 
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

func (q *Queries) CreateChirp(ctx context.Context, body string, userID uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, CreateChirp, body, userID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const GetChirps = `-- name: GetChirps :many
SELECT id, created_at, updated_at, body, user_id
FROM chirps
ORDER BY created_at ASC
`

func (q *Queries) GetChirps(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, GetChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var chirps []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.Body, &i.UserID); err != nil {
			return nil, err
		}
		chirps = append(chirps, i)
	}
	return chirps, nil
}

const GetChirp = `-- name: GetChirp :one
SELECT id, created_at, updated_at, body, user_id
FROM chirps
WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, GetChirp, id)
	var i Chirp
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.Body, &i.UserID)
	if err != nil {
		return Chirp{}, err
	}
	return i, nil
}